
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " ~I The job was automatically triggered by a{{{{ github.event_nam}}}} event."
      - run: echo " M-' This job is now running on {{${{ runner.}} }} server hosted by GitHub!"
      - run: echo " ~N The name of your branch is{{{{ github.re}}}} and your repository is{{{{ github.repositor}}}}."

