name: GitHub Actions Demo
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python script
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
        run: python job.py

      - name: Write a file
        run: echo "hello scp!" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mon-fichier
          path: output.txt

  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit tests
        run: python -m unittest test_addition.py
      - run: |
          mkdir ~/.ssh
          ssh-keyscan $HOST > ~/.ssh/known_hosts
          sshpass -p "$SSH_PASSWORD" scp addition.py ubuntu@$HOST
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HOST: 20.56.74.49

  Run-Unit-Tests-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mon-projet:test .

      - name: Run tests in container
        run: docker run --rm mon-projet:test